#!/usr/bin/env python3
"""The predicates, and the two ways a triple is written out as text.

Every string a reader will ever see is here. Nothing is generated by a model.
The text is layered, and each layer takes the triple as its input:

    a triple          subject IRI, predicate, object IRI
      -> N-Triples    the ordinary serialisation, always available
        -> a sentence a template filled with two labels, only where both
                      features carry a label in that language

The N-Triples layer is put first because it is the canonical form: it exists
for every true triple, so the places where a sentence is missing show up as an
absence beside a line that is present, rather than as a row that was never
written. A reader counting rows per form can see the label gap in the data.

The templates are written for areas, because every feature in this dataset is
an administrative area. A dataset that later holds a line or a point needs
different wording and should say so rather than reuse these.
"""

# The eight Simple Features predicates, in the order GeoSPARQL lists them.
SF = ("sfEquals", "sfDisjoint", "sfIntersects", "sfTouches",
      "sfWithin", "sfContains", "sfOverlaps", "sfCrosses")

# The eight RCC8 base relations. Exactly one holds of any pair, which is why
# they are a separate column rather than eight more rows.
RCC8 = ("DC", "EC", "PO", "EQ", "TPP", "NTPP", "TPPi", "NTPPi")

# The namespace the oracle's graphs already use for the predicates. Writing
# the IRIs out in full is what makes the N-Triples form self-contained: a
# reader, or a model, never has to carry a prefix table from somewhere else.
GEO = "http://www.opengis.net/ont/geosparql#"

# Predicates worth a sentence. sfIntersects is true of everything that is not
# disjoint and says little on its own; sfCrosses is never true between two
# areas. Both stay in the table and in the N-Triples form, and neither becomes
# a sentence.
SPOKEN = ("sfWithin", "sfContains", "sfTouches", "sfEquals", "sfOverlaps",
          "sfDisjoint")

# The forms a triple is written in, in the order they are layered.
FORMS = ("ntriples", "en", "ja")

# The two natural languages among the forms. Separated from FORMS so that
# adding a third language does not mean hunting for the places that assumed
# there were two.
LANGS = ("en", "ja")

TEMPLATES = {
    "sfWithin": {
        "en": "{a} is within {b}.",
        "ja": "{a}は{b}に含まれる。",
    },
    "sfContains": {
        "en": "{a} contains {b}.",
        "ja": "{a}は{b}を含む。",
    },
    "sfTouches": {
        "en": "{a} borders {b}.",
        "ja": "{a}は{b}と接している。",
    },
    "sfEquals": {
        "en": "{a} and {b} cover the same area.",
        "ja": "{a}と{b}は同じ範囲を占める。",
    },
    "sfOverlaps": {
        "en": "{a} and {b} overlap without either containing the other.",
        "ja": "{a}と{b}は重なるが、どちらも他方を含まない。",
    },
    "sfDisjoint": {
        "en": "{a} and {b} do not meet.",
        "ja": "{a}と{b}は接していない。",
    },
}

# For a triple the composition table entailed, the text says so and names the
# step it came through. Without that a reader cannot tell an observation from
# a deduction, and the whole point of keeping derivation is lost. The
# N-Triples form of the same row carries all three statements for the same
# reason: the two premises are what make the conclusion readable as a
# deduction rather than as one more observation.
COMPOSED = {
    "en": "{first} {second} Therefore {conclusion}",
    "ja": "{first}{second}したがって{conclusion}",
}

# Which Simple Features predicate says the same thing as an RCC8 relation, for
# the ones that have a sentence. TPP and NTPP are both "within"; the
# difference between them is whether the boundaries meet, which the matrix
# records and the sentence does not try to.
RCC8_TO_SF = {
    "DC": "sfDisjoint", "EC": "sfTouches", "PO": "sfOverlaps",
    "EQ": "sfEquals", "TPP": "sfWithin", "NTPP": "sfWithin",
    "TPPi": "sfContains", "NTPPi": "sfContains",
}


def nt_line(triple):
    """One N-Triples statement, from a triple's IRIs and predicate.

    A triple here is any mapping carrying subject_iri, predicate and
    object_iri. Taking the whole triple rather than three arguments keeps the
    two layers fed from the same object, so a sentence and the line above it
    cannot drift apart by one of them being handed different parts.
    """
    return (f'<{triple["subject_iri"]}> <{GEO}{triple["predicate"]}> '
            f'<{triple["object_iri"]}> .')


def nt_text(triples):
    """The N-Triples form of a row: one statement per line."""
    return "\n".join(nt_line(t) for t in triples)


def sentence(triple, labels, lang):
    """One sentence, or None when it cannot be written.

    None has three causes and they are deliberately not distinguished here,
    because the caller treats them the same: the predicate is not spoken, the
    language has no template, or a feature has no label in this language. A
    feature with no label gets no sentence rather than a romanisation passed
    off as that language.
    """
    t = TEMPLATES.get(triple["predicate"])
    if not t or lang not in t:
        return None
    a = labels.get((triple["subject_id"], lang))
    b = labels.get((triple["object_id"], lang))
    if not a or not b:
        return None
    return t[lang].format(a=a, b=b)


def sentence_text(triples, labels, lang):
    """The natural-language form of a row, or None if any part is missing.

    All or nothing: a composition row whose middle sentence cannot be written
    would otherwise become a two-sentence chain that reads as a deduction with
    a step removed, which is worse than not being there.
    """
    parts = [sentence(t, labels, lang) for t in triples]
    if any(p is None for p in parts):
        return None
    if len(parts) == 1:
        return parts[0]
    if len(parts) != 3:
        raise ValueError(f"a chain has one or three statements, got {len(parts)}")
    first, second, conclusion = parts
    return COMPOSED[lang].format(first=first, second=second,
                                 conclusion=conclusion)
